<Project>
  <!-- Common output directory for all projects -->
  <PropertyGroup>
    <OutputPath>$(MSBuildThisFileDirectory)bin\$(Configuration)\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <!-- Build as 64-bit for more memory -->
    <PlatformTarget>x64</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>

  <!-- Copy Shaders and icons folders to output directory after build -->
  <Target Name="CopySharedResources" AfterTargets="Build">
    <ItemGroup>
      <ShaderFiles Include="$(MSBuildThisFileDirectory)Shaders\**\*.*" />
      <IconFiles Include="$(MSBuildThisFileDirectory)icons\**\*.*" />
    </ItemGroup>
    <Copy SourceFiles="@(ShaderFiles)" DestinationFolder="$(OutputPath)Shaders\%(RecursiveDir)" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(IconFiles)" DestinationFolder="$(OutputPath)icons\%(RecursiveDir)" SkipUnchangedFiles="true" />
  </Target>
</Project>

